---
# SPDX-License-Identifier: MIT

name: dotfiles_cli
description: Dotfiles with Git hooks, Mac setup, security scanning, and version management.
version: 1.5.4
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  args: ^2.4.2

dev_dependencies:
  lints: ^3.0.0

executables:
  dotfiles:
