name: ollama tool ci

on:
  push:
    branches: [ main, add-ollama-tool ]
    paths:
      - 'ollama-tool/**'
      - '.github/workflows/ollama-tool.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'ollama-tool/**'
      - '.github/workflows/ollama-tool.yml'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: rust
      uses: dtolnay/rust-toolchain@stable

    - name: cache
      uses: Swatinem/rust-cache@v2

    - name: check
      uses: ./.github/actions/rust-check
      with:
        working-directory: ollama-tool